Load event sample for Kinesis events; Add com.amazonaws:aws-java-sdk-kinesis dependency (as run-time) because KinesisEvent relies on a class which is in that project (this indicates AWS maven projects have dependency issues) so that way the class is found at run-time and it does not fail with NoClassDefFoundError.